# Generated by Django 5.2.8 on 2025-11-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер категории')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория классификации',
                'verbose_name_plural': 'Категории классификации',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='ФИО или название организации отправителя', max_length=255, verbose_name='Отправитель')),
                ('subject', models.CharField(help_text='Краткая тема или заголовок письма', max_length=500, verbose_name='Тема письма')),
                ('original_text', models.TextField(verbose_name='Текст письма')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('summary', models.TextField(blank=True, help_text='Краткое содержание письма, сгенерированное нейросетью', verbose_name='Краткое содержание')),
                ('classification', models.IntegerField(blank=True, null=True, verbose_name='Классификация')),
                ('criticality_level', models.IntegerField(blank=True, choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Критический')], null=True, verbose_name='Уровень критичности')),
                ('response_style', models.IntegerField(blank=True, choices=[(1, 'Строгий официальный стиль'), (2, 'Деловой корпоративный стиль'), (3, 'Клиентоориентированный вариант'), (4, 'Краткий информационный ответ')], null=True, verbose_name='Стиль ответа')),
                ('processing_time_hours', models.IntegerField(blank=True, help_text='Примерное время, необходимое для обработку письма', null=True, verbose_name='Время на обработку (часы)')),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн по SLA')),
                ('final_response', models.TextField(blank=True, help_text='Текст ответа, который будет отправлен отправителю', verbose_name='Финальный ответ')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('analyzed', 'Проанализировано'), ('response_generated', 'Ответ сгенерирован'), ('done', 'Завершено'), ('archived', 'В архиве')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_style', models.IntegerField(choices=[(1, 'Строгий официальный стиль'), (2, 'Деловой корпоративный стиль'), (3, 'Клиентоориентированный вариант'), (4, 'Краткий информационный ответ')], verbose_name='Стиль ответа')),
                ('response_text', models.TextField(verbose_name='Текст ответа')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбран для отправки')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_letters.letter', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Сгенерированный ответ',
                'verbose_name_plural': 'Сгенерированные ответы',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_data', models.JSONField(verbose_name='Данные анализа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата анализа')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank_letters.letter', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Результат анализа',
                'verbose_name_plural': 'Результаты анализа',
            },
        ),
        migrations.CreateModel(
            name='LetterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ LLM')),
                ('asked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_letters.letter', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Вопрос к письму',
                'verbose_name_plural': 'Вопросы к письмам',
                'ordering': ['-asked_at'],
            },
        ),
    ]
